name       : rav1e
version    : 0.6.1
release    : 10
source     :
    - https://github.com/xiph/rav1e/archive/refs/tags/v0.6.1.tar.gz : dd12132ad9dac229ce00a9caad132c4ad23d7db2b3ad4b5a59e89658fee04d9a
    - https://github.com/xiph/rav1e/releases/download/v0.6.1/Cargo.lock : da13dcb2ea6bc0212b077a2e2e2e55b2a674a0ae683b7a2c4cf3e4f137c920cb
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
setup      : |
    cp $sources/Cargo.lock .
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr
