name       : rav1e
version    : 0.5.1
release    : 9
source     :
    - https://github.com/xiph/rav1e/archive/refs/tags/v0.5.1.tar.gz : 7b3060e8305e47f10b79f3a3b3b6adc3a56d7a58b2cb14e86951cc28e1b089fd
    - https://github.com/xiph/rav1e/releases/download/v0.5.1/Cargo.lock : 6baeb4e72ee86dd4c3d6c9acfcfac6a2e58a580101eb181daced09199a136868
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
setup      : |
    cp $sources/Cargo.lock .
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr
