name       : rav1e
version    : 0.4.0
release    : 4
source     :
    - https://github.com/xiph/rav1e/archive/v0.4.0.tar.gz : c3ea1a2275f09c8a8964084c094d81f01c07fb405930633164ba69d0613a9003
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
