name       : rav1e
version    : 0.6.2
release    : 11
source     :
    - https://github.com/xiph/rav1e/archive/refs/tags/v0.6.2.tar.gz : 8fe8d80bc80a05ee33113c0ee19779d9c57189e5434c8e1da8f67832461aa089
    - https://github.com/xiph/rav1e/releases/download/v0.6.2/Cargo.lock : 5f1f34a269322b8ec6c6432d6b928c72da254e16e65a0c8f81fe252367a99ba5
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
setup      : |
    cp $sources/Cargo.lock .
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr
