name       : rav1e
version    : 0.6.3
release    : 12
source     :
    - https://github.com/xiph/rav1e/archive/refs/tags/v0.6.3.tar.gz : 660a243dd9ee3104c0844a7af819b406193a7726614a032324557f81bb2bebaa
    - https://github.com/xiph/rav1e/releases/download/v0.6.3/Cargo.lock : f22049598eb6f9948b4d852850eeb48c1236a7a068692db85cbfe72b94498581
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
setup      : |
    cp $sources/Cargo.lock .
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr
