name       : rav1e
version    : 0.3.5
release    : 3
source     :
    - https://github.com/xiph/rav1e/archive/v0.3.5.tar.gz : ab97209f52695dce740cffb61b0f53b53db5682bfbdd1dfbaf8c93ee36a69a84
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
build      : |
    cargo cbuild --library-type=cdylib --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --prefix=/usr \
        --release
