name       : rav1e
version    : 0.3.3
release    : 1
source     :
    - https://github.com/xiph/rav1e/archive/v0.3.3.tar.gz : a091f3387055e472b6e028aa013cf0f37fb5acce9f4db2605d929bbffb448d01
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
build      : |
    cargo cbuild --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --prefix=/usr \
        --release

    rm -v $installdir/usr/lib64/librav1e.a
