name       : rav1e
version    : 0.4.1
release    : 5
source     :
    - https://github.com/xiph/rav1e/archive/refs/tags/v0.4.1.tar.gz : b0be59435a40e03b973ecc551ca7e632e03190b5a20f944818afa3c2ecf4852d
license    : BSD-2-Clause
component  : multimedia.codecs
summary    : The fastest and safest AV1 encoder
description: |
    rav1e is an AV1 video encoder. It is designed to eventually cover all use cases, though in its current form it is most suitable for cases where libaom (the reference encoder) is too slow.
builddeps  :
    - cargo-c
networking : yes
build      : |
    cargo cbuild \
        --library-type=cdylib \
        --locked \
        --release
install    : |
    cargo cinstall \
        --destdir=$installdir \
        --libdir=%libdir% \
        --library-type=cdylib \
        --locked \
        --prefix=/usr \
        --release
